/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QCarousel {
        "withScroll": boolean;
    }
    interface QScrollicon {
    }
}
declare global {
    interface HTMLQCarouselElement extends Components.QCarousel, HTMLStencilElement {
    }
    var HTMLQCarouselElement: {
        prototype: HTMLQCarouselElement;
        new (): HTMLQCarouselElement;
    };
    interface HTMLQScrolliconElement extends Components.QScrollicon, HTMLStencilElement {
    }
    var HTMLQScrolliconElement: {
        prototype: HTMLQScrolliconElement;
        new (): HTMLQScrolliconElement;
    };
    interface HTMLElementTagNameMap {
        "q-carousel": HTMLQCarouselElement;
        "q-scrollicon": HTMLQScrolliconElement;
    }
}
declare namespace LocalJSX {
    interface QCarousel {
        "withScroll"?: boolean;
    }
    interface QScrollicon {
    }
    interface IntrinsicElements {
        "q-carousel": QCarousel;
        "q-scrollicon": QScrollicon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "q-carousel": LocalJSX.QCarousel & JSXBase.HTMLAttributes<HTMLQCarouselElement>;
            "q-scrollicon": LocalJSX.QScrollicon & JSXBase.HTMLAttributes<HTMLQScrolliconElement>;
        }
    }
}
